spring:
  application:
    name: tms
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: zolotoy
    password: Bb752094
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
  #main:
    #allow-circular-references: true
application:
  jwt:
    secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
    expiration: 86400000 #day

  #spring.flyway.baseline-on-migrate=true
  #logging.level.org.springframework.orm.jpa=DEBUG
