spring:
  application:
    name: tms
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.H2Dialect
    database: postgresql
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    #main:
    #allow-circular-references: true
application:
  jwt:
    secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
    expiration: 86400000 #day